# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\MarkdownTransformer:
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    AppBundle\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\Form\TypeExtension\HelpFormExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    AppBundle\Service\MessageManager:
        arguments:
            - ['You can do it!', 'Dude, sweet!', 'Woot!']
            - ['We are *never* going to figure this out', 'Why even try again?', 'Facepalm']
        public: true
