version: '3.4'

services:
  nginx:
    build:
      context: docker/nginx
      target: base
    hostname: "www.code-symfony33.com"
    volumes:
      - ./start/:/var/www/
    depends_on:
      - php
    ports:
      - 8000:80
  php:
    build:
      context: docker/php
      target: base
      args:
        - IS_MAC=${IS_MAC}
        - UID=1000
        - GID=1000
    depends_on:
      - db
    volumes:
      - ./start/:/var/www/
  db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root
